### ISSUE TITLE
Generate a Stratification Variable to Identify Misfits in the Global Setting?

### ISSUE THREAD

**Issue by jwbowers** [acarril/randtreat#3]
We have been happy to be using randtreat for some of our study designs (at http://oes.gsa.gov). One question we have had recently is how to identify the strata for the misfits. For example in this code we get 6 misfits. 

```
 randtreat, generate(newtreat) strata(lgan size_cat) misfits(global)
*assignment produces 6 misfits
```
We have the variables of `lgan` and `size_cat` defined and we do not see any missing values on newtreat (using `tab newtreat, missing` or directly inspecting the 72 units in the data browser.

So, we wonder: where were those 6 misfits placed? Is there a way to create a new strata variable that would tell us this information?

We could do ` egen strata = concat(lgan size_cat)` but this does not tell us the strata for the misfits --- or which units were identified as misfits.

We'd appreciate any help.

**Comment by acarril** [comment]
In order to see the misfit values you can specify the misfits option with the argument missing:
`dsadsadsa`

**Comment by acarril** [comment]
In order to leave the misfit observations as missing you can specify the `misfits()` option with the argument `missing`:
```
randtreat, generate(newtreat) strata(lgan size_cat) misfits(missing)
```
Notice that this is the default, so if you just omit the `misfits()` option you'll get the same result.

**Comment by jwbowers** [comment]
Great. I see that the misfit status is assigned at random with equal probability within strata. Is that correct? This would explain why, without setting the seed, each run of randtreat creates a different set of misfits. Thanks much for teaching us about this!

**Comment by acarril** [comment]
That is exactly correct, and very much on purpose. You're welcome!

If you want additional details on the different methods to deal with misfits, I suggest you read the [corresponding article](http://www.stata-journal.com/article.html?article=st0490) (direct pdf link [here](https://www.dropbox.com/s/os7f4zohdtt2zap/sjart_st0490.pdf?dl=0)).

**Comment by jwbowers** [comment]
Great. Thanks again for explaining.
